@startuml

start

switch ( threads number )
case ( equal 1 )
  :1 thread;
case ( equal 2 ) 
  :2 thread;
case ( equal 3 )
  :3 thread;
case ( equal 4 )
  :4 thread
  ----
  emergency
  end
  kill;
  kill
case ( equal 5 )
  :5 thread;
endswitch

stop

@enduml
